/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.eddii;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco Pagoaga
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        carreras.leer();
        investigadores.leer();
        publicaciones.leer();
        proyectos.leer();
        setTablaCarrera();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estado = new javax.swing.ButtonGroup();
        EstadoProyecto = new javax.swing.ButtonGroup();
        AgregarCarrera = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombrecarrera = new javax.swing.JTextField();
        activo = new javax.swing.JRadioButton();
        inactivo = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        AgregarInvestigador = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreInvestigador = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        activoinvetsigador = new javax.swing.JRadioButton();
        inactivoinvestigador = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        AgregarProyecto = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nombreproyecto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        iniciado = new javax.swing.JRadioButton();
        enviado = new javax.swing.JRadioButton();
        publicado = new javax.swing.JRadioButton();
        rechazado = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        AgregarPublicacion = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombrepublicacion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        ModificarCarrera = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nombrecarrera1 = new javax.swing.JTextField();
        activo1 = new javax.swing.JRadioButton();
        inactivo1 = new javax.swing.JRadioButton();
        jButton13 = new javax.swing.JButton();
        ModificarInvestigador = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        NombreInvestigador1 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        activoinvetsigador1 = new javax.swing.JRadioButton();
        inactivoinvestigador1 = new javax.swing.JRadioButton();
        jButton14 = new javax.swing.JButton();
        ModificarProyecto = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        nombreproyecto1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        iniciado1 = new javax.swing.JRadioButton();
        enviado1 = new javax.swing.JRadioButton();
        publicado1 = new javax.swing.JRadioButton();
        rechazado1 = new javax.swing.JRadioButton();
        jButton15 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        ModificarPublicacion = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        nombrepublicacion1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Estado:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Ingrese Datos de Carrera");

        Estado.add(activo);
        activo.setText("Acvtiva");

        Estado.add(inactivo);
        inactivo.setText("Inactiva");

        jButton9.setText("Agregar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarCarreraLayout = new javax.swing.GroupLayout(AgregarCarrera.getContentPane());
        AgregarCarrera.getContentPane().setLayout(AgregarCarreraLayout);
        AgregarCarreraLayout.setHorizontalGroup(
            AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCarreraLayout.createSequentialGroup()
                .addGroup(AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(AgregarCarreraLayout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel3))
                        .addGroup(AgregarCarreraLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AgregarCarreraLayout.createSequentialGroup()
                                    .addComponent(activo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inactivo)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(nombrecarrera))))
                    .addGroup(AgregarCarreraLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton9)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        AgregarCarreraLayout.setVerticalGroup(
            AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarCarreraLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombrecarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(AgregarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(activo)
                    .addComponent(inactivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(45, 45, 45))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Ingrese Datos de Investigador");

        jLabel5.setText("Nombre (30 bytes)");

        jLabel6.setText("Fecha de Ingreso:");

        jLabel7.setText("Carrera:");

        jLabel8.setText("Estado:");

        Estado.add(activoinvetsigador);
        activoinvetsigador.setText("Activo");

        Estado.add(inactivoinvestigador);
        inactivoinvestigador.setText("Inactivo");

        jButton10.setText("Agregar Investigador");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarInvestigadorLayout = new javax.swing.GroupLayout(AgregarInvestigador.getContentPane());
        AgregarInvestigador.getContentPane().setLayout(AgregarInvestigadorLayout);
        AgregarInvestigadorLayout.setHorizontalGroup(
            AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                .addGroup(AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel4))
                    .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(NombreInvestigador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addGroup(AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(activoinvetsigador)
                                .addGap(18, 18, 18)
                                .addComponent(inactivoinvestigador)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarInvestigadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10)
                        .addGap(172, 172, 172)))
                .addGap(23, 23, 23))
        );
        AgregarInvestigadorLayout.setVerticalGroup(
            AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NombreInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(AgregarInvestigadorLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(AgregarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(activoinvetsigador)
                            .addComponent(inactivoinvestigador))))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Ingrese Datos de Proyectos");

        jLabel10.setText("Nombre/Tema (50 bytes)");

        jLabel11.setText("Fecha de Inicio:");

        jLabel12.setText("Fecha de Fin:");

        jLabel13.setText("Estado:");

        EstadoProyecto.add(iniciado);
        iniciado.setText("Iniciado");

        EstadoProyecto.add(enviado);
        enviado.setText("Enviado");

        EstadoProyecto.add(publicado);
        publicado.setText("Publicado");

        EstadoProyecto.add(rechazado);
        rechazado.setText("Rechazado");

        jButton11.setText("Agregar Proyecto");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel32.setText("Investigador");

        javax.swing.GroupLayout AgregarProyectoLayout = new javax.swing.GroupLayout(AgregarProyecto.getContentPane());
        AgregarProyecto.getContentPane().setLayout(AgregarProyectoLayout);
        AgregarProyectoLayout.setHorizontalGroup(
            AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarProyectoLayout.createSequentialGroup()
                .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarProyectoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarProyectoLayout.createSequentialGroup()
                                .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11))
                                .addGap(27, 27, 27)
                                .addComponent(iniciado)
                                .addGap(18, 18, 18)
                                .addComponent(enviado)
                                .addGap(18, 18, 18)
                                .addComponent(publicado)
                                .addGap(18, 18, 18))
                            .addGroup(AgregarProyectoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)))
                        .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarProyectoLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addComponent(rechazado)))
                    .addGroup(AgregarProyectoLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel9))
                    .addGroup(AgregarProyectoLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jButton11)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        AgregarProyectoLayout.setVerticalGroup(
            AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(nombreproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(AgregarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(iniciado)
                    .addComponent(enviado)
                    .addComponent(publicado)
                    .addComponent(rechazado))
                .addGap(37, 37, 37)
                .addComponent(jButton11)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Inserte Datos de la Publicacion");

        jLabel15.setText("Revista/Conferencia (20 bytes)");

        jLabel16.setText("Proyecto:");

        jLabel17.setText("Fecha:");

        jButton12.setText("Agregar Publicacion");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarPublicacionLayout = new javax.swing.GroupLayout(AgregarPublicacion.getContentPane());
        AgregarPublicacion.getContentPane().setLayout(AgregarPublicacionLayout);
        AgregarPublicacionLayout.setHorizontalGroup(
            AgregarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgregarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarPublicacionLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(nombrepublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(AgregarPublicacionLayout.createSequentialGroup()
                        .addGroup(AgregarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AgregarPublicacionLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addContainerGap(146, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarPublicacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(AgregarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarPublicacionLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarPublicacionLayout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addGap(146, 146, 146))))))
        );
        AgregarPublicacionLayout.setVerticalGroup(
            AgregarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(AgregarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nombrepublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel18.setText("Nombre:");

        jLabel19.setText("Estado:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Ingrese Datos a Modificar de Carrera");

        Estado.add(activo1);
        activo1.setText("Acvtiva");
        activo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activo1ActionPerformed(evt);
            }
        });

        Estado.add(inactivo1);
        inactivo1.setText("Inactiva");

        jButton13.setText("Agregar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarCarreraLayout = new javax.swing.GroupLayout(ModificarCarrera.getContentPane());
        ModificarCarrera.getContentPane().setLayout(ModificarCarreraLayout);
        ModificarCarreraLayout.setHorizontalGroup(
            ModificarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarCarreraLayout.createSequentialGroup()
                .addGroup(ModificarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarCarreraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ModificarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(ModificarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ModificarCarreraLayout.createSequentialGroup()
                                .addComponent(activo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inactivo1)
                                .addGap(0, 249, Short.MAX_VALUE))
                            .addComponent(nombrecarrera1)))
                    .addGroup(ModificarCarreraLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jButton13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarCarreraLayout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(41, 41, 41))
        );
        ModificarCarreraLayout.setVerticalGroup(
            ModificarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarCarreraLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(ModificarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(nombrecarrera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ModificarCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(activo1)
                    .addComponent(inactivo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addGap(45, 45, 45))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Ingrese Datos a Modificar de Investigador");

        jLabel22.setText("Nombre (30 bytes)");

        jLabel23.setText("Fecha de Ingreso:");

        jLabel24.setText("Carrera:");

        jLabel25.setText("Estado:");

        Estado.add(activoinvetsigador1);
        activoinvetsigador1.setText("Activo");

        Estado.add(inactivoinvestigador1);
        inactivoinvestigador1.setText("Inactivo");

        jButton14.setText("Agregar Investigador");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarInvestigadorLayout = new javax.swing.GroupLayout(ModificarInvestigador.getContentPane());
        ModificarInvestigador.getContentPane().setLayout(ModificarInvestigadorLayout);
        ModificarInvestigadorLayout.setHorizontalGroup(
            ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                .addGroup(ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addComponent(NombreInvestigador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addGroup(ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(activoinvetsigador1)
                                .addGap(18, 18, 18)
                                .addComponent(inactivoinvestigador1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarInvestigadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton14)
                        .addGap(172, 172, 172)))
                .addGap(23, 23, 23))
            .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModificarInvestigadorLayout.setVerticalGroup(
            ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(33, 33, 33)
                .addGroup(ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(NombreInvestigador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(ModificarInvestigadorLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(ModificarInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(activoinvetsigador1)
                            .addComponent(inactivoinvestigador1))))
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Ingrese Datos a Modificar de Proyectos");

        jLabel27.setText("Nombre/Tema (50 bytes)");

        jLabel28.setText("Fecha de Inicio:");

        jLabel29.setText("Fecha de Fin:");

        jLabel30.setText("Estado:");

        EstadoProyecto.add(iniciado1);
        iniciado1.setText("Iniciado");

        EstadoProyecto.add(enviado1);
        enviado1.setText("Enviado");

        EstadoProyecto.add(publicado1);
        publicado1.setText("Publicado");

        EstadoProyecto.add(rechazado1);
        rechazado1.setText("Rechazado");

        jButton15.setText("Agregar Proyecto");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel31.setText("Investigador");

        javax.swing.GroupLayout ModificarProyectoLayout = new javax.swing.GroupLayout(ModificarProyecto.getContentPane());
        ModificarProyecto.getContentPane().setLayout(ModificarProyectoLayout);
        ModificarProyectoLayout.setHorizontalGroup(
            ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarProyectoLayout.createSequentialGroup()
                .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarProyectoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarProyectoLayout.createSequentialGroup()
                                .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28))
                                .addGap(27, 27, 27)
                                .addComponent(iniciado1)
                                .addGap(18, 18, 18)
                                .addComponent(enviado1)
                                .addGap(18, 18, 18)
                                .addComponent(publicado1)
                                .addGap(18, 18, 18))
                            .addGroup(ModificarProyectoLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreproyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)))
                        .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rechazado1)
                            .addGroup(ModificarProyectoLayout.createSequentialGroup()
                                .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ModificarProyectoLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jButton15))
                    .addGroup(ModificarProyectoLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel26)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        ModificarProyectoLayout.setVerticalGroup(
            ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarProyectoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nombreproyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(ModificarProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(iniciado1)
                    .addComponent(enviado1)
                    .addComponent(publicado1)
                    .addComponent(rechazado1))
                .addGap(37, 37, 37)
                .addComponent(jButton15)
                .addContainerGap())
        );

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setText("Inserte Datos a Modificar de la Publicacion");

        jLabel34.setText("Revista/Conferencia (20 bytes)");

        jLabel35.setText("Proyecto:");

        jLabel36.setText("Fecha:");

        jButton16.setText("Agregar Publicacion");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarPublicacionLayout = new javax.swing.GroupLayout(ModificarPublicacion.getContentPane());
        ModificarPublicacion.getContentPane().setLayout(ModificarPublicacionLayout);
        ModificarPublicacionLayout.setHorizontalGroup(
            ModificarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarPublicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModificarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarPublicacionLayout.createSequentialGroup()
                        .addGroup(ModificarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarPublicacionLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel36))
                        .addContainerGap(146, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarPublicacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton16)
                        .addGap(146, 146, 146))
                    .addGroup(ModificarPublicacionLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(nombrepublicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificarPublicacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33)
                .addContainerGap())
        );
        ModificarPublicacionLayout.setVerticalGroup(
            ModificarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarPublicacionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(nombrepublicacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ModificarPublicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Crear Carrera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar Carrera");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(170, 170, 170))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carreras", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Crear Investigador");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar Investigador");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton18.setText("Buscar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(121, 121, 121))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton18)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Investigadores", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton5.setText("Crear Proyecto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Modificar Proyecto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton19.setText("Buscar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(157, 157, 157))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton19)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton19)
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Proyectos", jPanel3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton7.setText("Crear Publicacion");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Modificar Publicacion");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jButton7)
                        .addGap(160, 160, 160)
                        .addComponent(jButton8)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Publicaciones", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgregarCarrera.pack();
        AgregarCarrera.setLocationRelativeTo(this);
        AgregarCarrera.setModal(true);
        AgregarCarrera.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (!nombrecarrera.getText().equals("")&&(activo.isSelected()==true || inactivo.isSelected()==true)) {
            try {
                int estado;
                if (activo.isSelected()) {
                    estado=1;
                }else{
                    estado=0;
                }
                carreras.getCarreras().add(new Carrera(carreras.getCarreras().size()+1,nombrecarrera.getText(),estado));
                JOptionPane.showMessageDialog(AgregarCarrera, "Carrera creada");
                setTablaCarrera();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(AgregarCarrera, "Supera el numero de Bytes");
            }
            AgregarCarrera.dispose();
        }else{
            JOptionPane.showMessageDialog(AgregarCarrera,"Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:
                setTablaCarrera();
                break;
            case 1:
                setTablaInvestigadores();
                break;
            case 2:
                setTablaProyectos();
                break;
            case 3:
                setTablaPublicaciones();
                break;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!NombreInvestigador.getText().equals("")&&(activoinvetsigador.isSelected()==true||activoinvetsigador.isSelected()==true)) {
            try {
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fecha=sdf.format(jCalendar1.getDate());
                System.out.println(fecha);
                int selectedvalue=Integer.parseInt(jComboBox1.getSelectedItem().toString());
                int activo;
                if (activoinvetsigador.isSelected()) {
                    activo=1;
                }else{
                    activo=0;
                }
                investigadores.getInvestigadores().add(new Investigador(investigadores.getInvestigadores().size()+1,NombreInvestigador.getText(),fecha,selectedvalue,activo));
                JOptionPane.showMessageDialog(AgregarInvestigador, "Investigador creado");
                setTablaInvestigadores();
                AgregarInvestigador.dispose();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(AgregarInvestigador, "Supera el numero de Bytes");
            }
        }else{
            JOptionPane.showMessageDialog(AgregarInvestigador, "Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ComboModelCarrera(jComboBox1);
        AgregarInvestigador.pack();
        AgregarInvestigador.setLocationRelativeTo(this);
        AgregarInvestigador.setModal(true);
        AgregarInvestigador.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (!nombreproyecto.getText().equals("")&&(iniciado.isSelected()||enviado.isSelected()||publicado.isSelected()||rechazado.isSelected())) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fechainicio=sdf.format(jCalendar2.getDate());
                String fechafin=sdf.format(jCalendar3.getDate());
                int selectedvalue=Integer.parseInt(jComboBox5.getSelectedItem().toString());
                int estado=-1;
                if (iniciado.isSelected()) {
                    estado=0;
                }else if (enviado.isSelected()) {
                    estado=1;
                }else if (publicado.isSelected()) {
                    estado=2;
                }else if (rechazado.isSelected()) {
                    estado=3;
                }
                proyectos.getProyectos().add(new Proyecto(proyectos.getProyectos().size()+1,nombreproyecto.getText(),selectedvalue,fechainicio,fechafin,estado));
                JOptionPane.showMessageDialog(AgregarProyecto, "Proyecto creado");
                setTablaProyectos();
                AgregarProyecto.dispose();
            } catch (Exception e) {
            }
        }else{
            JOptionPane.showMessageDialog(AgregarProyecto, "Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ComboModelInvestigador(jComboBox5);
        AgregarProyecto.pack();
        AgregarProyecto.setLocationRelativeTo(this);
        AgregarProyecto.setModal(true);
        AgregarProyecto.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (!nombrepublicacion.getText().equals("")&&(jCalendar4.getDate()!=null)) {
            try {
                int selectedvalue=Integer.parseInt(jComboBox2.getSelectedItem().toString());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fecha=sdf.format(jCalendar4.getDate());
                publicaciones.getPublicaciones().add(new Publicaciones(publicaciones.getPublicaciones().size()+1,selectedvalue,fecha,nombrepublicacion.getText()));
                JOptionPane.showMessageDialog(AgregarPublicacion, "Publicacion Agregada");
                setTablaPublicaciones();
                AgregarPublicacion.dispose();
            } catch (Exception e) {
            }
        }else{
            JOptionPane.showMessageDialog(AgregarPublicacion, "Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ComboModelProyecto(jComboBox2);
        AgregarPublicacion.pack();
        AgregarPublicacion.setLocationRelativeTo(this);
        AgregarPublicacion.setModal(false);
        AgregarPublicacion.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (!nombrecarrera1.getText().equals("")&&(activo1.isSelected()==true||inactivo1.isSelected()==true)) {
            try {
                int activo=-1;
                if (activo1.isSelected()) {
                    activo=0;
                }else if (activo1.isSelected()) {
                    activo=1;
                }
                
                Carrera reemplazo=new Carrera(Integer.parseInt(carreras.getCarreras().get(jTable1.getSelectedRow()).getCodigo().getNombre()),nombrecarrera1.getText(),activo);
                carreras.getCarreras().set(jTable1.getSelectedRow(),reemplazo);
                setTablaCarrera();
                ModificarCarrera.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(ModificarCarrera, "Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void activo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activo1ActionPerformed

    }//GEN-LAST:event_activo1ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (!NombreInvestigador1.getText().equals("")&&(activoinvetsigador1.isSelected()==true||activoinvetsigador1.isSelected()==true)) {
            try {
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fecha=sdf.format(jCalendar5.getDate());
                int selectedvalue=Integer.parseInt(jComboBox3.getSelectedItem().toString());
                int activo;
                if (activoinvetsigador1.isSelected()) {
                    activo=1;
                }else{
                    activo=0;
                }
                Investigador reemplazo=new Investigador(Integer.parseInt(investigadores.getInvestigadores().get(jTable2.getSelectedRow()).getCodigo().getNombre()),NombreInvestigador1.getText(),fecha,selectedvalue,activo);
                investigadores.getInvestigadores().set(jTable2.getSelectedRow(),reemplazo);
                JOptionPane.showMessageDialog(AgregarInvestigador, "Investigador Modificado");
                setTablaInvestigadores();
                ModificarInvestigador.dispose();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(AgregarInvestigador, "Supera el numero de Bytes");
            }
        }else{
            JOptionPane.showMessageDialog(AgregarInvestigador, "Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (!nombreproyecto1.getText().equals("")&&(iniciado1.isSelected()||enviado1.isSelected()||publicado1.isSelected()||rechazado1.isSelected())) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fechainicio=sdf.format(jCalendar6.getDate());
                String fechafin=sdf.format(jCalendar7.getDate());
                int selectedvalue=Integer.parseInt(jComboBox4.getSelectedItem().toString());
                int estado=-1;
                if (iniciado1.isSelected()) {
                    estado=0;
                }else if (enviado1.isSelected()) {
                    estado=1;
                }else if (publicado1.isSelected()) {
                    estado=2;
                }else if (rechazado1.isSelected()) {
                    estado=3;
                }
                Proyecto reemplazo=new Proyecto(Integer.parseInt(proyectos.getProyectos().get(jTable3.getSelectedRow()).getCodigo().getNombre()),nombreproyecto1.getText(),selectedvalue,fechainicio,fechafin,estado);
                proyectos.getProyectos().set(jTable3.getSelectedRow(),reemplazo);
                JOptionPane.showMessageDialog(AgregarProyecto, "Proyecto creado");
                setTablaProyectos();
                ModificarProyecto.dispose();
            } catch (Exception e) {
            }
        }else{
            JOptionPane.showMessageDialog(AgregarProyecto, "Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (!nombrepublicacion1.getText().equals("")&&(jCalendar8.getDate()!=null)) {
            try {
                int selectedvalue=Integer.parseInt(jComboBox6.getSelectedItem().toString());
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String fecha=sdf.format(jCalendar8.getDate());
                Publicaciones reemplazo=new Publicaciones(Integer.parseInt(publicaciones.getPublicaciones().get(jTable4.getSelectedRow()).getCodigo().getNombre()),selectedvalue,fecha,nombrepublicacion1.getText());
                publicaciones.getPublicaciones().set(jTable4.getSelectedRow(), reemplazo);
                JOptionPane.showMessageDialog(AgregarPublicacion, "Publicacion Modificada");
                setTablaPublicaciones();
                ModificarPublicacion.dispose();
            } catch (Exception e) {
            }
        }else{
            JOptionPane.showMessageDialog(AgregarPublicacion, "Llene todos los espacios");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getSelectedRow()!=-1) {
            ModificarCarrera.pack();
            ModificarCarrera.setLocationRelativeTo(null);
            ModificarCarrera.setModal(true);
            ModificarCarrera.setVisible(true);
        }else{
           JOptionPane.showMessageDialog(this, "Eliga un elemento de la lista");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTable2.getSelectedRow()!=-1) {
            ComboModelCarrera(jComboBox3);
            ModificarInvestigador.pack();
            ModificarInvestigador.setModal(true);
            ModificarInvestigador.setVisible(true);
        }else{
           JOptionPane.showMessageDialog(this, "Eliga un elemento de la lista");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jTable3.getSelectedRow()!=-1) {
            ComboModelInvestigador(jComboBox4);
            ModificarProyecto.pack();
            ModificarProyecto.setLocationRelativeTo(this);
            ModificarProyecto.setModal(true);
            ModificarProyecto.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Eliga un elemento de la lista");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jTable4.getSelectedRow()!=-1) {
            ComboModelProyecto(jComboBox6);
            ModificarPublicacion.pack();
            ModificarPublicacion.setLocationRelativeTo(this);
            ModificarPublicacion.setModal(true);
            ModificarPublicacion.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Eliga un elemento de la lista");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AgregarCarrera;
    private javax.swing.JDialog AgregarInvestigador;
    private javax.swing.JDialog AgregarProyecto;
    private javax.swing.JDialog AgregarPublicacion;
    private javax.swing.ButtonGroup Estado;
    private javax.swing.ButtonGroup EstadoProyecto;
    private javax.swing.JDialog ModificarCarrera;
    private javax.swing.JDialog ModificarInvestigador;
    private javax.swing.JDialog ModificarProyecto;
    private javax.swing.JDialog ModificarPublicacion;
    private javax.swing.JTextField NombreInvestigador;
    private javax.swing.JTextField NombreInvestigador1;
    private javax.swing.JRadioButton activo;
    private javax.swing.JRadioButton activo1;
    private javax.swing.JRadioButton activoinvetsigador;
    private javax.swing.JRadioButton activoinvetsigador1;
    private javax.swing.JRadioButton enviado;
    private javax.swing.JRadioButton enviado1;
    private javax.swing.JRadioButton inactivo;
    private javax.swing.JRadioButton inactivo1;
    private javax.swing.JRadioButton inactivoinvestigador;
    private javax.swing.JRadioButton inactivoinvestigador1;
    private javax.swing.JRadioButton iniciado;
    private javax.swing.JRadioButton iniciado1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private java.awt.List list1;
    private javax.swing.JTextField nombrecarrera;
    private javax.swing.JTextField nombrecarrera1;
    private javax.swing.JTextField nombreproyecto;
    private javax.swing.JTextField nombreproyecto1;
    private javax.swing.JTextField nombrepublicacion;
    private javax.swing.JTextField nombrepublicacion1;
    private javax.swing.JRadioButton publicado;
    private javax.swing.JRadioButton publicado1;
    private javax.swing.JRadioButton rechazado;
    private javax.swing.JRadioButton rechazado1;
    // End of variables declaration//GEN-END:variables
    AdmCarrera carreras=new AdmCarrera();
    AdmProyecto proyectos=new AdmProyecto();
    AdmPublicaciones publicaciones=new AdmPublicaciones();
    AdmInvestigadores investigadores=new AdmInvestigadores();
    
    private void setTablaCarrera(){
        DefaultTableModel model;
        String Carrera[]={"ID","Nombre de la Carrera","Estado"};
        String data[][]=new String[carreras.getCarreras().size()][3];
        for (int i = 0; i < carreras.getCarreras().size(); i++) {
            data[i][0]=carreras.getCarreras().get(i).getCodigo().getNombre();
            data[i][1]=carreras.getCarreras().get(i).getNombre().getNombre();
            if (carreras.getCarreras().get(i).getEstado().getNombre()=="1") {
                data[i][2]="Activo";
            }else{
                data[i][2]="Inactivo";
            }
        }
        model=new DefaultTableModel(data,Carrera);
        jTable1.setModel(model);
    }
    
    private void setTablaInvestigadores(){
        DefaultTableModel model;
        String investigador[]={"Codigo","Nombre","Fecha de Ingreso","Carrera de Pertenencia","Estado"};
         String data[][]=new String[this.investigadores.getInvestigadores().size()][5];
         for (int i = 0;  i<investigadores.getInvestigadores().size () ; i++) {
            data[i][0]=investigadores.getInvestigadores().get(i).getCodigo().getNombre();
            data[i][1]=investigadores.getInvestigadores().get(i).getNombre().getNombre();
            data[i][2]=investigadores.getInvestigadores().get(i).getFechadeingreso().getNombre();
            data[i][3]=investigadores.getInvestigadores().get(i).getCodigo_carrera().getNombre();
            if (carreras.getCarreras().get(i).getEstado().getNombre()=="1") {
                data[i][4]="Activo";
            }else{
                data[i][4]="Inactivo";
            }
        }
        model=new DefaultTableModel(data,investigador);
        jTable2.setModel(model);
    }
    
    private void setTablaProyectos(){
        DefaultTableModel model;
        String proyecto[]={"Codigo","Nombre","Codigo Investigador","Fecha Inicio","FechaFin","Estado"};
        String data[][]=new String[proyectos.getProyectos().size()][6];
        for (int i = 0; i < this.proyectos.getProyectos().size(); i++) {
            data[i][0]=proyectos.getProyectos().get(i).getCodigo().getNombre();
            data[i][1]=proyectos.getProyectos().get(i).getNombre().getNombre();
            data[i][2]=proyectos.getProyectos().get(i).getCodigo_investigador().getNombre();
            data[i][3]=proyectos.getProyectos().get(i).getFecha_inicio().getNombre();
            data[i][4]=proyectos.getProyectos().get(i).getFecha_fin().getNombre();
            if (proyectos.getProyectos().get(i).getEstado().getNombre().equals("0")) {
                data[i][5]="Iniciado";
            }else if (proyectos.getProyectos().get(i).getEstado().getNombre().equals("1")) {
                data[i][5]="Enviado";
            }else if (proyectos.getProyectos().get(i).getEstado().getNombre().equals("2")) {
                data[i][5]="Publicado";
            }else if (proyectos.getProyectos().get(i).getEstado().getNombre().equals("3")) {
                data[i][5]="Rechazado";
            }
        }
        model=new DefaultTableModel(data,proyecto);
        jTable3.setModel(model);
    }
    
    private void setTablaPublicaciones(){
        DefaultTableModel model;
        String publicacion[]={"Codigo","Revista / Conferencia","Fecha","Codigo de Proyecto"};
        String data[][]=new String[publicaciones.getPublicaciones().size()][5];
        for (int i = 0; i < publicaciones.getPublicaciones().size(); i++) {
            data[i][0]=publicaciones.getPublicaciones().get(i).getCodigo().getNombre();
            data[i][1]=publicaciones.getPublicaciones().get(i).getRevista().getNombre();
            data[i][2]=publicaciones.getPublicaciones().get(i).getFecha().getNombre();
            data[i][3]=publicaciones.getPublicaciones().get(i).getCodigo_de_proyecto().getNombre();
        }
        model=new DefaultTableModel(data,publicacion);
        jTable4.setModel(model);
    }
    
    private void ComboModelCarrera(JComboBox combobox){
        try {
            String model[]=new String[carreras.getCarreras().size()];
            for (int i = 0; i < carreras.getCarreras().size(); i++) {
                model[i]=carreras.getCarreras().get(i).getCodigo().getNombre();
            }
            DefaultComboBoxModel mod=new DefaultComboBoxModel(model);
            combobox.setModel(mod);
        } catch (Exception e) {
        }
    }
    
    private void ComboModelInvestigador(JComboBox combobox){
        try {
            String model[]=new String[investigadores.getInvestigadores().size()];
            for (int i = 0; i < investigadores.getInvestigadores().size(); i++) {
                model[i]=investigadores.getInvestigadores().get(i).getCodigo().getNombre();
            }
            DefaultComboBoxModel mod=new DefaultComboBoxModel(model);
            combobox.setModel(mod);
        } catch (Exception e) {
        }
    }
   
    private void ComboModelProyecto(JComboBox combobox){
        try {
            String model[]=new String[proyectos.getProyectos().size()];
            for (int i = 0; i < proyectos.getProyectos().size(); i++) {
                model[i]=proyectos.getProyectos().get(i).getCodigo().getNombre();
            }
            DefaultComboBoxModel mod=new DefaultComboBoxModel(model);
            combobox.setModel(mod);
        } catch (Exception e) {
        }
    }
    
}
